
services:
  locus-fulguris:
      build: .
      container_name: locus-fulguris
      restart: unless-stopped
      networks:
      - default
      - public_net
      env_file: ".env"
networks:
  public_net:
    external: true